---
name: ♻️ pre-commit Update

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit-update:
    name: pre-commit Update
    permissions:
      contents: write
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-pre-commit-update.yml@72f9c303ec3becced97e2d4472122fee783ff4a4 # v8.0.1
