---
name: ♻️ pre-commit Update

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit-update:
    name: pre-commit Update
    permissions:
      contents: write
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-pre-commit-update.yml@bc0d450d55cc014693437d793b797b7b0e281db4 # v7.3.1
