---
name: ♻️ Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@8465086d84a8ae8fb993ef582f00cf13b8ceb9c8 # v7.1.0
    with:
      super-linter-variables: |
        {
          "FILTER_REGEX_EXCLUDE": "(app/static/javascript/(chart\\.umd-4\\.4\\.0\\.min\\.js|govuk-frontend-5\\.1\\.0\\.min\\.js|govuk-frontend-5\\.9\\.0\\.min\\.js|moj-frontend\\.min\\.js)|helm/modernisation-platform-ui/templates/)",
          "VALIDATE_CSS": false,
          "VALIDATE_CSS_PRETTIER": false,
          "VALIDATE_EDITORCONFIG": false,
          "VALIDATE_HTML": false,
          "VALIDATE_HTML_PRETTIER": false,
          "VALIDATE_JAVASCRIPT_ES": false,
          "VALIDATE_JAVASCRIPT_PRETTIER": false,
          "VALIDATE_JSCPD": false,
          "VALIDATE_MARKDOWN": false,
          "VALIDATE_MARKDOWN_PRETTIER": false,
          "VALIDATE_PYTHON_BLACK": false,
          "VALIDATE_PYTHON_PYLINT": false,
          "VALIDATE_PYTHON_FLAKE8": false,
          "VALIDATE_PYTHON_ISORT": false,
          "VALIDATE_PYTHON_MYPY": false,
          "VALIDATE_PYTHON_RUFF": false,
          "VALIDATE_YAML": false,
          "FIX_PYTHON_RUFF_FORMAT": true
        }
