---
name: ♻️ Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-dependency-review.yml@bc0d450d55cc014693437d793b797b7b0e281db4 # v7.3.1
